apiVersion: v1
kind: Pod
metadata:
  labels:
    run: worker-app-pod
    app: demo-voting-app
  name: worker-app-pod
spec:
  containers:
  - image: kodekloud/examplevotingapp_worker:v1
    name: worker-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
